# Config file for automatic testing at travis-ci.org

branches:
  # Exclude some branches (whose names start with WIP) from travis
  except:
    - /^(WIP).*$/

language: python

# Need to use python 3.7 (date: 20190707)
dist: xenial

# Start x virtual framebuffer for gui
services:
  - xvfb

addons:
  apt:
    packages:
    # Needed to start x virtual framebuffer (this is not the right way...)
    - libxcb1
    - libxkbcommon-x11-0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xinerama0

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DIST=pypi
  - DIST=anaconda

jobs:
  fast_finish: true


install:
  - >
    if [ "$DIST" == "anaconda" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      sed -i s/PyQt5\>/pyqt\>/g requirements.txt;
      conda create -q -n pyinductcondaenv python=$TRAVIS_PYTHON_VERSION --file requirements.txt;
      sed -i s/pyqt\>/PyQt5\>/g requirements.txt;
      source activate pyinductcondaenv;
      python setup.py install;
      pip install codecov;
      conda list;
    else
      pip install --upgrade pip;
      pip install ".[tests]";
      pip list;
    fi;

script:
  #- export QT_DEBUG_PLUGINS=1;
  - coverage run --omit="pyinduct/tests/*" -m pyinduct.tests.run_tests --no-plots;

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.8" && "$DIST" == "pypi" ]]; then
      codecov;
    fi
